# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(200, 50))
A

array([[64,  0, 30, ..., 34, 18, 51],
       [62, 81, 33, ...,  7, 73, 43],
       [62,  1, 31, ..., 81, 15, 93],
       ...,
       [78, 59, 59, ..., 90, 64, 14],
       [37, 40,  7, ..., 98, 38, 98],
       [97, 33, 89, ..., 12, 63, 63]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [16]:
#Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке.

A = np.random.randint(0, 100, size=(200, 50))
np.random.shuffle(A.T)
print(A)

[[72 91 59 ... 30 87  2]
 [89 77 81 ... 27 34 17]
 [70 20  0 ... 56  6 18]
 ...
 [66 56  8 ... 15 99  7]
 [ 1  0 73 ... 80 23 34]
 [36 59  5 ... 69 32  2]]


# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [23]:
#Generate a new array that contains only those rows of array `A` in which:
# - the sum of elements in even columns (indexes 0, 2,...) is greater than the average value (across the entire array) of the sum of elements in odd columns (indexes 1, 3,...).

A = np.random.randint(0, 100, size=(200, 50))
B = A[:, ::2]
C = A[:, 1::2]
D = B.sum(axis=1) > C.sum(axis=1).mean()
print(A[D])




[[72  8 94 ...  2 65 12]
 [94 93 87 ... 81 85 74]
 [33 68 48 ... 48 23 50]
 ...
 [79 14 41 ... 49 12 61]
 [66 75  1 ... 46 49 70]
 [50 23 87 ... 95 17 29]]


# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [24]:
# Find the index of the array string `A` in which the difference between the maximum and minimum element is maximal.

A = np.random.randint(0, 100, size=(200, 50))
B = A.max(axis=1) - A.min(axis=1)
print(B.argmax())


15


# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [37]:
# Generate an array of the same dimension as `A`, but in which each element is replaced by its ordinal number (starting from 1) in an ascending array of `A` elements.

A = np.random.randint(0, 100, size=(200, 50))
B = np.sort(A, axis=None)
C = np.argsort(B)
print(C.reshape(A.shape))
print(A)



[[   0   81   80 ...   91   90   89]
 [  88   87   86 ...   51   39   38]
 [  37   36   35 ...  196  195  194]
 ...
 [9811 9810 9809 ... 9967 9959 9964]
 [9958 9948 9956 ... 9911 9910 9909]
 [9908 9907 9906 ... 9917 9929 9999]]
[[13 98 35 ... 83 93 70]
 [ 7 17  7 ... 87  1 84]
 [73 26 44 ...  7 56 57]
 ...
 [95  2 19 ... 68 71 18]
 [24 60 15 ... 17 52 59]
 [14 34 20 ... 28 76 32]]


# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [38]:
# Apply min-max normalization to the rows of array `A'. 
# That is, you need to get a new array, in each row of which the maximum element is 1, the minimum is 0.

A = np.random.randint(0, 100, size=(200, 50))
B = A.max(axis=1)
C = A.min(axis=1)
D = (A - C[:, np.newaxis]) / (B - C)[:, np.newaxis]
print(D)


[[0.05102041 0.29591837 0.12244898 ... 0.60204082 0.56122449 0.98979592]
 [0.90721649 0.21649485 0.96907216 ... 0.57731959 0.24742268 0.90721649]
 [0.76666667 0.23333333 0.         ... 0.25555556 0.77777778 0.01111111]
 ...
 [0.         0.8172043  0.25806452 ... 0.34408602 0.90322581 0.61290323]
 [0.4742268  0.09278351 0.55670103 ... 0.54639175 0.60824742 0.11340206]
 [0.33333333 0.         0.29292929 ... 0.74747475 0.06060606 0.11111111]]


# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [39]:
# Generate a new three-dimensional array of dimensions 10x200x50. The subarrays along the zero axis should consist of elements `A` multiplied by 1 - 10, respectively.

A = np.random.randint(0, 100, size=(200, 50))
B = np.arange(1, 11)
C = A * B[:, np.newaxis, np.newaxis]
print(C.shape)
print(C)


(10, 200, 50)
[[[ 76  18  66 ...  55   2  50]
  [  2  83  21 ...  87  70   3]
  [ 51  14  85 ...  18   1  88]
  ...
  [  5  22  58 ...  58  16  82]
  [ 23  67  24 ...  79  74   1]
  [ 65  27  87 ...  10  60  12]]

 [[152  36 132 ... 110   4 100]
  [  4 166  42 ... 174 140   6]
  [102  28 170 ...  36   2 176]
  ...
  [ 10  44 116 ... 116  32 164]
  [ 46 134  48 ... 158 148   2]
  [130  54 174 ...  20 120  24]]

 [[228  54 198 ... 165   6 150]
  [  6 249  63 ... 261 210   9]
  [153  42 255 ...  54   3 264]
  ...
  [ 15  66 174 ... 174  48 246]
  [ 69 201  72 ... 237 222   3]
  [195  81 261 ...  30 180  36]]

 ...

 [[608 144 528 ... 440  16 400]
  [ 16 664 168 ... 696 560  24]
  [408 112 680 ... 144   8 704]
  ...
  [ 40 176 464 ... 464 128 656]
  [184 536 192 ... 632 592   8]
  [520 216 696 ...  80 480  96]]

 [[684 162 594 ... 495  18 450]
  [ 18 747 189 ... 783 630  27]
  [459 126 765 ... 162   9 792]
  ...
  [ 45 198 522 ... 522 144 738]
  [207 603 216 ... 711 666   9]
  [585 243 783

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [40]:
# Create a new array of the same dimension as `A`, in which the even columns of `A` are grouped first, then the odd ones. Use [np.concat()] (https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html).

A = np.random.randint(0, 100, size=(200, 50))
B = A[:, ::2]
C = A[:, 1::2]
D = np.concatenate((B, C), axis=1)
print(D)


[[65 35 22 ... 48 48 92]
 [83 74 65 ... 50  5 72]
 [91 62 11 ... 51 75 74]
 ...
 [54 39 48 ... 38 12 37]
 [31 79 40 ... 72 30 56]
 [49 37 28 ... 12 69 30]]


# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [41]:
# Count the number of rows of the array `A`, in which all elements are greater than 5. Use [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = A > 5
C = np.all(B, axis=1)
print(C.sum())



7


# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [42]:
# Divide the array `A` horizontally into 10 parts and create a new array of dimension 20x50, which is the average of these parts. Use [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = np.split(A, 10, axis=0)
C = np.mean(B, axis=0)
print(C.shape)
print(C)



(20, 50)
[[52.4 50.3 46.1 23.8 34.3 58.7 44.  43.2 53.  61.3 50.  51.5 41.4 55.
  58.1 63.5 43.8 55.2 39.6 58.4 45.6 49.4 51.9 40.2 52.7 42.5 60.7 25.
  43.6 56.7 48.5 42.1 51.  44.1 44.4 44.4 52.8 43.8 57.5 53.2 63.7 60.3
  42.7 58.1 43.3 51.1 57.4 52.8 66.  48.5]
 [51.4 42.9 52.5 65.9 55.5 57.4 30.7 44.3 36.3 56.6 50.5 53.7 46.3 34.1
  52.7 49.5 43.1 61.3 54.4 39.6 28.5 51.5 39.5 30.3 61.1 41.7 51.2 45.3
  53.  33.1 19.9 47.4 50.4 46.1 55.2 34.3 55.3 55.3 59.2 30.7 58.9 57.1
  48.5 49.8 53.3 38.4 50.9 53.5 35.9 46.8]
 [40.  37.6 55.1 46.  32.6 46.4 54.2 44.9 48.6 64.3 38.5 52.7 58.8 47.7
  43.5 49.5 47.6 53.5 54.1 47.8 44.3 49.4 39.3 37.9 55.5 58.3 53.1 44.4
  55.4 55.5 40.3 45.1 43.6 43.5 51.1 46.8 60.6 46.3 54.4 54.4 48.7 32.9
  58.4 45.3 43.2 40.7 43.2 62.6 54.1 45.7]
 [51.8 46.6 27.4 49.2 51.1 55.  54.9 45.7 56.  42.6 38.7 63.  48.1 44.7
  49.5 50.  50.6 52.1 57.4 49.1 60.  42.8 59.6 64.2 54.5 27.9 63.1 50.1
  33.5 50.9 42.4 41.  53.6 32.1 59.2 45.3 37.7 46.3 58.8 53.5 47.5 56.1


# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [43]:
#"Expand" the array `A` into a one-dimensional array. Leave only the unique elements in it in the same order in which they occur in the array. Use [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = np.unique(A)
print(B.shape)
print(B)



(100,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [47]:
# Create a one-dimensional array of dimension 200, in which each element is the Euclidean distance between the corresponding row `A` and the "middle" row `A`. Use [np.linalg.norm()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = A.mean(axis=0)
C = np.sqrt(((A - B) ** 2).sum(axis=1))
print(C.shape)
print(C)

(200,)
[221.49482838 182.54821007 186.80982041 186.85052582 204.82687568
 194.85294198 189.69728253 212.59870414 221.88102443 183.13775962
 192.12256244 200.55151209 204.40454741 192.47550234 217.44422043
 187.73792638 177.69847777 212.00398345 224.21897556 199.10371418
 188.38927517 190.22799216 191.28512488 186.48911228 204.5176985
 221.91727963 208.68233993 208.20631355 208.39661466 205.75570223
 216.35435979 210.18926947 220.43177856 214.99218358 203.6454247
 205.87192378 202.50510858 213.5730999  208.90050024 209.74958641
 195.3878681  199.53235076 179.6765121  210.58235681 186.44355446
 192.20670904 217.58607262 200.26197592 201.66600854 198.86366938
 187.92780263 218.19903529 190.84810452 193.65370898 196.71911193
 204.06819693 204.95094291 198.91035418 195.1116834  207.41855992
 217.76108238 193.84400687 219.08208279 222.14911434 210.4186755
 196.14644784 210.83123345 181.76982423 212.2590375  177.3223026
 209.60536491 200.21857806 208.72378638 225.94665078 192.25573854
 216.03

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [48]:
# Create a new array that consists of `A` elements modified according to the following rules:
# - if the element is less than 50, then it is multiplied by 2;
# - otherwise it is multiplied by 3.
# Use [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html ).

A = np.random.randint(0, 100, size=(200, 50))
B = np.where(A < 50, A * 2, A * 3)
print(B)


[[162 294 162 ...  20 273 168]
 [291 207 213 ...  14 261 216]
 [ 60 153  74 ... 171  88 252]
 ...
 [ 26  40 297 ... 231  92 198]
 [ 60 207 162 ...  40 219  28]
 [ 98  74 231 ...  52  14 174]]


# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [49]:
# Expand the array `A` into a one-dimensional array. Create three new arrays by calculating the moving averages of the windows 3, 5, 10. Find the sum of these arrays by aligning from the dimension with zeros on the right
# *Tip: Implement a function that counts the moving average. Use [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html ) or [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html )*

A = np.random.randint(0, 100, size=(200, 50))
B = np.concatenate((A, np.zeros((2, 50))), axis=0)
C = np.cumsum(B, axis=0)
D = C[3:] - C[:-3]
E = np.cumsum(B, axis=0)
F = E[5:] - E[:-5]
G = np.cumsum(B, axis=0)
H = G[10:] - G[:-10]
print(D.sum(axis=0))
print(F.sum(axis=0))
print(H.sum(axis=0))


[30077. 27857. 30708. 31583. 28727. 27592. 30392. 28082. 30683. 29798.
 29869. 29056. 28704. 30129. 28258. 29948. 27679. 28839. 29570. 29897.
 30200. 29426. 30527. 27891. 28620. 28482. 30096. 30083. 31795. 27305.
 29412. 27693. 31682. 27559. 28392. 30009. 28416. 29730. 28977. 29718.
 28613. 30295. 30173. 30806. 27866. 31968. 28822. 26230. 28841. 25832.]
[49533. 46174. 50728. 52132. 47311. 45634. 50267. 46501. 50587. 49209.
 49181. 47919. 47537. 49804. 46867. 49417. 45662. 47762. 48958. 49243.
 50009. 48667. 50642. 45932. 47145. 46937. 49824. 49758. 52412. 45159.
 48563. 46003. 52490. 45602. 47090. 49601. 47037. 49030. 47737. 49226.
 47475. 49832. 49853. 50798. 46060. 52786. 47660. 43384. 47782. 42729.]
[ 96580.  90566.  99062. 101157.  92079.  89484.  98197.  90570.  98423.
  95975.  95796.  92953.  92768.  96771.  92076.  95492.  88689.  93202.
  95506.  96369.  97722.  94611.  98369.  89227.  91521.  90824.  97203.
  97304. 101697.  88175.  95375.  89578. 102825.  88915.  92733.  971

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [52]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)  




[0, 0, 0, 4, 4]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

In [73]:
# Implement this algorithm in a more optimal way on `numpy` arrays, without using loops. Check the correctness and identity of sampling algorithms using statistical tests.
def sample(x: np.ndarray, c: int) -> np.ndarray:
    assert len(x) > 0
    
    s = np.sum(x)
    val = s * np.random.random(size=c)
    idx = np.searchsorted(np.cumsum(x), val)
    return idx

# test
sample(np.array([50, 3, 1, 7, 20]), 5)


array([1, 4, 4, 0, 0])

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [68]:
import random
import timeit 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)
# compare performance (using,`time it').
timeit.timeit('walk(10_000)', globals=globals(), number=1000)

5.983520091998798

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

In [75]:
# Implement a more efficient version using `numpy`, compare performance (using, for example, magic `time it'). Using [kdeplot()](https://seaborn.pydata.org/generated/seaborn .kdeplot.html ) or analogs, plot the distribution of the values of `walk(10_000)` on some reasonable number of launches.

import timeit
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import random


def walk_numpy(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += np.random.choice([-3, -1, 0, 2, 3])

    return cur_position

# test function walk_numpy
walk_numpy(10_000)
# compare performance (using,`time it').
timeit.timeit('walk_numpy(10_000)', globals=globals(), number=1000)



177.481662193004

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [76]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


0.8225643261795775

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.

In [19]:
# optimize function strange_conv using `Numba` and compare performance.ResourceWarning

import numba as nb
import numpy as np 
import numpy.typing as npt
import timeit

@nb.njit
def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t

a = np.random.random((10000, 10000))
strange_conv(a)

-0.15339751792773595